language: cpp

compiler:
  - clang
  - gcc

before_script:
  - sh ./scripts/ArangoDB/arangodb_startup.sh
  - sudo apt-add-repository -y ppa:canonical-qt5-edgers/qt5-proper
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes clang-3.2
  - sudo apt-get install -qq --force-yes qt5-qmake qtbase5-dev qt5-default
  - bash ./scripts/travis-ci/build-driver.sh

script:
  - bash ./scripts/travis-ci/build-tests.sh
